config/routes.rb
Rails.application.routes.draw do

  root 'posts#new'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :users

  resources :posts

  resources :sessions

end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user

	has_attached_file :photo, styles: { medium: "400x400>", thumb: "100x100>" }, default_url: "images/:style/missing.png"
	validates_attachment_content_type :photo, content_type: /\Aimage\/.*\Z/

end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :posts

	has_secure_password
	validates_confirmation_of :password
	validates_presence_of :password, on: :create
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    # current_user
    @post = Post.new
  end

  def create
    # current_user
    @post = Post.new(post_params)
    @post.save
    redirect_to post_path(@post)
  end

  def index
    # current_user
    @posts = Post.all
  end

  def show
    # current_user
    @post = Post.find(params[:id])
  end

  def update
  end

  def edit
  end

  def destroy
  end

  private

  def post_params
    params.require(:post).permit(:artist, :caption, :city, :date, :user_id, :photo)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	@user = User.find_by_email(params[:email])
    if @user && user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to root_path, :notice => "Welcome back to InstaJam, #{@user.email}"
    else
      flash[:alert] = "Invalid email and/or password. Please try again!"
      render 'new'
    end
  end

  def destroy
  	session.clear
    redirect_to users_path
    flash[:alert] = "Bye Bye"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    # current_user
    @user = User.find_by_email(params[:email])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to root_path, :notice => "Welcome to InstaJam, #{@user.email}!"
    else
      flash[:alert] = "Invalid email and/or password. Please try again!"
      render "new"
    end
  end

  def show
    # current_user
    @user = User.find(params[:id])
  end

  def index
    # current_user
    @users = User.all.reverse
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h2 class="subhead">Sign In</h2>

<br>
<h2 class="subhead">New to InstaJam? <%= link_to "Sign Up Here!", new_user_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>InstaJam</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="wrapper">
<h1 class="banner">InstaJam</h1>
</div>

<%= yield %>

</body>
</html>

app/views/posts/edit.html.erb
<h1>Posts#edit</h1>
<p>Find me in app/views/posts/edit.html.erb</p>

app/views/posts/index.html.erb
<% @posts.each do |p| %>
	<span class="subhead"><%= link_to p.artist, post_path(p.id) %></span>
	<br>
	<%= image_tag p.photo.url(:thumb) %>
	<br>
	<hr>
<% end %>
<%= link_to "Post a Photo", new_post_path %>

app/views/posts/new.html.erb
<h2 class="subhead">Post your photo!</h2>
<div class="body">
	<%= form_for @post, html: { multipart: true } do |f| %>
		<%= f.label :artist %>
		<%= f.text_field :artist %>
		<br>
		<%= f.label :caption %>
		<%= f.text_field :caption %>
		<br>
		<%= f.label :city %>
		<%= f.text_field :city %>
		<br>
		<%= f.label :date %>
		<%= f.date_field :date %>
		<br>
		<%= f.label :photo %>
		<%= f.file_field :photo %>
		<br>
		<%= f.submit %>
	<% end %>
</div>

app/views/posts/show.html.erb
<div class="body">
	<h2 class="subhead"><%= @post.artist %></h2>
	<%= image_tag @post.photo.url(:medium) %>
	<br>
	<%= @post.caption %>
	<br>
	<%= @post.city %>, <%= @post.date %>
	<br>
	<%= link_to "Post a Photo", new_post_path %>
	<br>
	<%= link_to "See All the Photos", posts_path %>
</div>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<h2 class="subhead">Please enter the following:</h2>
<div class="body">
	<%= form_for @user do |f| %>
		<%= f.label :email %>
		<%= f.text_field :email %>
		<br>
		<%= f.label :password %>
		<%= f.password_field :password %>
		<br>
		<%= f.submit %>
	<% end %>
</div>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>